### PR TITLE
Attachment upload

### PR DESCRIPTION
**Pull request by supernova2468**
##### Checklist

- [x] `mage test` passes
- [x] unit tests are included and tested
- [x] documentation is added or changed

Documentation is auto generated from comments, so I assume that is fulfilled. I needed the ability to upload attachments to a page. Since it uses the special multipart/form-data it needed a whole new function built out. Unit tests added and has been integration tested independently. Works as expected where you can feed it a io reader with whatever data you want. I've tried strings and png files personally.

### CODE REVIEW

**Comment by supernova2468** [comment]
Looks like the automated build tries to do something with the examples. Those looks to be pretty out of date, should not of been affected by anything I did. I'm not sure how the previous build was passing.

**Comment by supernova2468** [comment]
@cseeger-epages Hello?

**Comment by cseeger-epages** [comment]
@supernova2468 sorry for the long delay ill review it

**Comment by cseeger-epages** [comment]
LGTM. Thanks for your great contribution!

**Pull request merged**
